name: Hello World Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-run-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.vijayanandk }}
          password: ${{ secrets.Vijay@@docker0987 }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.vijayanandk }}/hello-world:latest .

      - name: Run Docker container (print hello world)
        run: docker run ${{ secrets.vijayanandk }}/hello-world:latest

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.vijayanandk }}/hello-world:latest
