# .github/workflows/docker-hello-world.yml

name: Build and Run Hello World Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (optional if you want to push)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.vijayanandk }}
          password: ${{ secrets.dokcer }}

      - name: Build Docker image
        run: docker build -t hello-world-image .

      - name: Run Docker container
        run: docker run hello-world-image
